"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest


@pytest.fixture
def scitex_dev_cli_or_skip():
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    return shutil.which("scitex-dev")


def test_audit_all_reports_no_violations_for_package(scitex_dev_cli_or_skip):
    # Arrange
    from scitex_dev.testing import audit_all_for_package

    completed_without_error = False
    # Act
    audit_all_for_package("scitex-types")
    completed_without_error = True
    # Assert
    assert completed_without_error
